### ISSUE TITLE
Uncaught DOMException: Failed to execute 'postMessage' on 'Worker

### ISSUE THREAD

**Issue by arifje** [ArteGEIE/videojs-vast#40]
![Screenshot 2023-07-13 at 12 14 07](https://github.com/ArteGEIE/videojs-vast/assets/1286410/eaf82439-c4d2-4c9a-b951-5c0e50a8d502)

**Comment by anurag-shj** [comment]
> ![Screenshot 2023-07-13 at 12 14 07](https://private-user-images.githubusercontent.com/1286410/253244011-eaf82439-c4d2-4c9a-b951-5c0e50a8d502.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NjU3MTEsIm5iZiI6MTcwMTg2NTQxMSwicGF0aCI6Ii8xMjg2NDEwLzI1MzI0NDAxMS1lYWY4MjQzOS1jNGQyLTRjOWEtYjk1MS01YzBlNTBhOGQ1MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDZUMTIyMzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWNiMjliMmE2NzQ4ODMzYmYxM2VhYWU0NjBjYzU0Mzg0NjNiMzA3NGUyYTNkNjczZWRhZDBmMTE3YWRjMTZiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4nYxhJpivEIZo5JlsgYY9kLISD4N4QQOZ4e_qWq4udA)

@arifje could you please help me to resolve this issue, I'm also getting a same error:
DOMException: Failed to execute 'postMessage' on 'Worker': () => _platformInjector = null could not be cloned.
    at TrackOrderDetailsComponent.initializeWebWorker (http://localhost:4200/src_app_modules_home_home_module_ts.js:24235:19)
    at http://localhost:4200/src_app_modules_home_home_module_ts.js:23789:24
    at _ZoneDelegate.invoke (http://localhost:4200/polyfills.js:8279:160)
    at Object.onInvoke (http://localhost:4200/vendor.js:180267:25)
    at _ZoneDelegate.invoke (http://localhost:4200/polyfills.js:8279:48)
    at Zone.run (http://localhost:4200/polyfills.js:8005:37)
    at http://localhost:4200/polyfills.js:9425:28
    at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:8312:173)
    at Object.onInvokeTask (http://localhost:4200/vendor.js:180255:25)
    at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:8312:56)
